name: Test
on:
  push:
    branches:
       - '*'
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run linters
        run: npm run lint
  notify-failure:
    runs-on: ubuntu-latest
    needs: [test,linters]
    if: failure()
    name: Notify-Failure
    steps:
      - name: Notify
        uses: pcvg/slack-notification-action@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          JOB_STATUS: Failure
          TITLE_MSG_FAIL: "Workflow failed - Zvezdochki!"
          URL_WORKFLOW: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"
          FOOTER_MSG_FAIL: "Failed - ${{ github.actor }}'s workflow in <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ github.repository }}>"
