name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm i
      - name: Run test
        run: npm test
      - name: Notify
        if: always()
        uses: pcvg/slack-notification-action@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          JOB_STATUS: ${{ job.status }}
          TITLE_MSG_SUCCESS: "Test completed!"
          TITLE_MSG_FAIL: "Workflow failed!"
          TITLE_MSG_CANCELLED: "Workflow canceled!"
          URL_WORKFLOW: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"
          FOOTER_MSG_SUCCESS: "${{ github.actor }}'s test was completed in <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ github.repository }}>"
          FOOTER_MSG_FAIL: "Failed - ${{ github.actor }}'s workflow in <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ github.repository }}>"
          FOOTER_MSG_CANCELLED: "${{ github.actor }}'s workflow cancelled in <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ github.repository }}>"
